//===================================================================
// COPYRIGHT amcbridge 2021/03/26
//===================================================================
// MyWindow.cpp
// Header definition of class MyWindow
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/03/26 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef MyWindow_H
#define MyWindow_H


#include "CATDlgDocument.h" 

#include "CATDialog.h"

#include "CATDlgDialog.h"
//-----------------------------------------------------------------------

class CATDlgPushButton;

class MyWindow : public CATDlgDialog
{
	DeclareResource(MyWindow, CATDlgDialog)
public:
// Standard constructors and destructors
// -------------------------------------
MyWindow (CATDialog * iParent, const CATString& iDialogName);
virtual ~MyWindow ();

void Build();

CATDlgPushButton *PushButton1111;

//
// TODO: Add your methods for this class here.
//

private:
// Copy constructor and equal operator
// -----------------------------------
MyWindow (MyWindow &);
MyWindow& operator=(MyWindow&);

};

//-----------------------------------------------------------------------

#endif
